language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: src/RetentionService.sln
script:
  - dotnet build src/RetentionService.sln -c Release
  - ls src/*Tests/*Tests.csproj | xargs -L1 dotnet test --no-build -c Release
