image: Visual Studio 2017

configuration: Release

before_build:
  - cmd: cd ./src
  - nuget restore

build:
  verbosity: minimal

only_commits:
  files:
    - appveyor.yml
    - src/

skip_commits:
  files:
    - docs/*
    - '**/*.md'
    - .gitignore
    - .travis.yml